# Generated by Django 5.1.6 on 2025-02-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
