# Generated by Django 5.1.6 on 2025-02-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept')], default='pending', max_length=10),
        ),
    ]
