# Generated by Django 5.1.6 on 2025-02-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_bookingrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='from_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
