# Generated by Django 5.1.6 on 2025-02-18 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingrequest_from_date_bookingrequest_to_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingrequest',
            old_name='from_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='bookingrequest',
            old_name='to_date',
            new_name='start_date',
        ),
    ]
